[workspace]
resolver = "2"
members = [
    "crates/libbadcpu",
    "crates/libloader",
    "crates/sober-services",
    "crates/sober-core",
    "crates/arm64jit",
    "crates/egl-wrapper",
    "crates/glesv2-wrapper",
    "crates/input-wrapper",
]

[workspace.package]
version = "0.1.0-dev"
edition = "2024"
license = "MIT"
