[package]
name = "libloader"
version.workspace = true
edition = "2021"
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
libc = "0.2"
nix = { version = "0.29", features = [
    "process",
    "signal",
    "fs",
    "mount",
    "sched",
    "user",
] }
anyhow = "1"
tracing = "0.1"
libbadcpu = { path = "../libbadcpu" }